### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by BurnhamR** [Minecraft-Modded-War/Hbm-s-Nuclear-Tech-GIT#1]
- [ ] Removing Various Entities that are not needed
- [ ] Minimizing Particles to avoid player FPS Lag
- [ ] Remove Armour
- [ ] Add config option for structure loot
- [ ] Add more config options
- [ ] Redoing missile system
- [ ] Redoing Machine stuff
- [ ] Redoing structure generation
- [ ] Optimize recipes 
- [ ] Optimize machines
- [ ] Add config option for machines power, usage, etc
- [ ] Attempt to associate player to explosion
- [ ] Attempt to redo NBT data on crates/machines/containers
- [ ] Optimize Explosions
- [ ] Optimize/Compress Texture Files
- [ ] Minify JSON Files
- [ ] Remove quackos/Ducks/Golden Eggs
- [ ] Remove some bombs
- [ ] Remove some particles
- [ ] Texture power lines black instead of red
- [ ] Fix tile entities
- [ ] Have a good config by default
- [ ] Add option for no metor damage
- [ ] Remove crazy OP items/Blackholes
- [ ] Fix HBM Radiation and stuff breaking invincible objects
- [ ] Remove Peas and various useless items
- [ ] Remove needing to go to nether, Make nether ores spawn in overworld.
- [ ] Update to latest HBM 1.7.10 features
